name: Build & Publish
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node: [8.x, 13.x]
    steps:
    - uses: actions/checkout@master
    
    - name: Set NodeJS ${{ matrix.node }}
      uses: actions/setup-node@master
      with:
        node-version: ${{ matrix.node }}

    - name: npm install
      run: npm install

    - name: lint
      run: npm run lint
      if: matrix.os == 'ubuntu-latest' && matrix.node == '13.x'

    - name: publish
      if: matrix.os == 'ubuntu-latest' && matrix.node == '13.x'
      env:
        NPM_CONFIG_TOKEN: ${{ secrets.NPM_CONFIG_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: npx custom-publish
